### ISSUE TITLE
Setup regolith environment

### ISSUE THREAD

**Issue by andyrichardson** [andyrichardson/dotfiles#1]
## Todo

 - [ ] Setup [emoji keyboard](https://www.reddit.com/r/unixporn/comments/c6i0f6/i3_custom_emoji_selector_menu_with_rofi/)
 - [ ] Setup i3 renaming script
 - [ ] Setup Super+backspace for closing windows
 - [ ] Cleanup old config files
